server:
  port: 1000
eureka:
  instance:
    hostname: wbxxx
  client:
    register-with-eureka: false  #是否要注册到eureka
    fetch-registry: false  #表示是否从Eureka Server获取注册信息
    serviceUrl:
      defaultZone: http://127.0.0.1:1000/eureka/
spring:
  application:
    name: AIGOU_EUREKA

